os:
  - linux
  - osx

language: go

go:
    - 1.8

install: true

before_install:
  - make deps

script:
  - go vet
  - go build

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
